### ISSUE TITLE
Use more specific path to ignore .next build dir in eslintignore as well?

### ISSUE THREAD

**Issue by willjw3** [chingu-voyages/v8-bears-team-06#16]
Just for the sake of consistency, should the same change be made to eslintignore as well? Or, should we leave it as long as there are no problems?

**Comment by hitochan777** [comment]
Good point. 
Actually it will not be an issue with this setting. With the current setting, it ignores all .next files or directories. but it's not likely to create .next files or directories that you don't want eslint or prettier to ignore.
yeah but for consistency, i will use the same setting as prettier

**Comment by willjw3** [comment]
Sounds good.
