### ISSUE TITLE
Do We Really Need Nexus For This Project?

### ISSUE THREAD

**Issue by willjw3** [chingu-voyages/v8-bears-team-06#29]
I was wondering,... Is it necessary to use nexus for this application; it seems like it's more than we need and the effort to go beyond getting comfortable with GraphQL and actually get comfortable with nexus and prisma may not be worth whatever benefits using it might offer.

**Comment by picklu** [comment]
Good question.  I think we all need to think about the stack and discuss it in the next meeting. But, please keep in mind that anything that is new to us will take time and we all have our comfort zone too.

**Comment by allanapplebee** [comment]
correct me if I'm wrong, but I think what @willjw3 is saying is just scrap it entirely, not replace it with something, so we wouldn't need to learn anything else. 

I tend to agree, seems like overkill - I'm guessing we're not going to need to deal with 1,000+ requests per second

**Comment by willjw3** [comment]
@allanapplebee,
Yes, that’s right. I’m wondering if it would be better to scrap it. I think we’d be fine with a schema file in which object types, queries and mutations were defined in the vanilla/standard way that most tutorials and apps I’ve checked out have used. 
If our product takes off and we need to scale things up, we might find the motivation to dig in deeper and implement it :)

**Comment by picklu** [comment]
@allanapplebee @willjw3 agreed.

**Comment by hitochan777** [comment]
I am sorry for not keeping up with the conversation.
Yeah I totally agree with you guys.
I just wanted to take this opportunity to try something very new, but considering the learning cost and given time, we should focus on finishing MVP.

**Comment by willjw3** [comment]
Thanks, guys, for your candor. We'll try a vanilla GraphQL approach that is in line with the standard educational material out there for basic usage. Once we're all comfortable with that approach, I'm sure that in the future we'll become more adventurous and look to use new and different GraphQL libraries.
