### ISSUE TITLE
Bootstrap Errors and no Mobile Responsiveness

### ISSUE THREAD

**Issue by willjw3** [chingu-voyages/v8-bears-team-06#36]
As @picklu pointed out, using just Bootstrap, in the way in which it was implemented, was problematic. In fact, we had no mobile-responsiveness as it was. 
I added the popper.js and jQuery  <script>s and added a toggler icon and dropdown capability to the navbar making it mobile responsive.
I used the Bootstrap stylesheet link from getBootstrap.com and the "Uncaught TypeError: Cannot read property 'fn' of undefined" error disappeared.
So now the the stylesheet link and three js Bootstrap <script>s come from the same source, and things are working nicely with no errors.

Base code will reflect this changes as soon as PR #35 is approved.

**Comment by willjw3** [comment]
I added
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
```
to the code in `Layout.jsx`, and I added the toggle icon and dropdown capability making the original navbar mobile responsive, so I'm withdrawing my request to use React Bootstrap for now and closing this issue.

**Comment by hitochan777** [comment]
Is it easy to customize the design?
One advantage of using the original bootstrap is that we can add whatever classes that we wants and thus we were able to customize the design easily.

**Comment by willjw3** [comment]
I'm reopening this to make everyone aware of the problem we have with Bootstrap in the base code right now. I've withdrawn my request to use React Bootstrap and have fixed the Bootstrap problem locally. Those changes will be reflected in the base code once PR #35 is approved.
@hitochan777 You're right, and I've implemented original Bootstrap in the appropriate way. Cheers!
