### ISSUE TITLE
Need a Prototype 'Work' Page

### ISSUE THREAD

**Issue by willjw3** [chingu-voyages/v8-bears-team-06#47]
This will be a page where a user can showcase a single project he/she was involved in.
User stories:
- User can add a title to the work in a 'Title' field
- User can enter a start date and an end date for the work in a 'Dates' field (implement a dropdown menu?)
- User can enter a description of the 'Work' (location, charity organization, the work done) in a 'Description' field.
- User can their thoughts about the experience in a 'My Thoughts on This Experience' field.
- Logged in Visitors can 'Like' the 'Work'

Anything else that should be included in the MVP? Maybe users should be able to upload an image related to the project?

**Comment by hitochan777** [comment]
Implemented in #70 and #58
