### ISSUE TITLE
Unit Testing of React Component with Jest

### ISSUE THREAD

**Issue by hitochan777** [chingu-voyages/v8-bears-team-06#6]

**Comment by hitochan777** [comment]
What library are you considering for react component testing?

For your information, these are famous libraries;

- [react testing library](https://github.com/kentcdodds/react-testing-library)
- [Enzyme](https://github.com/airbnb/enzyme)

**Comment by willjw3** [comment]
It looks like react testing library is the best way to go; seems easy to work with and there's plenty of information on usage via video and blog tutorials, for example. I'll work on it.

**Comment by hitochan777** [comment]
You'd better keep this issue open, because your PR is not merged yet.

**Comment by willjw3** [comment]
Merge conflict resolved. Still not passing Circle CI checks.
